base_local_planner: "dwa_local_planner/DWAPlannerROS"


DWAPlannerROS:
  # acceleration limits (handcrafted)
  acc_lim_x: 0.5
  acc_lim_y: 0.5
  acc_lim_trans: 0.5
  acc_lim_theta: 1.0

  # velocity limits (measured, physical limit)
  max_vel_trans: 0.48
  min_vel_trans: 0.0

  max_vel_x: 0.48
  min_vel_x: 0.0  # no backward driving!
  
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta: 1.11
  min_vel_theta: 0.0  # !!! (-1.11 ?)

  # simulation params
  sim_time: 2.0  # seconds
  vx_samples: 20
  vy_samples: 1
  vth_samples: 20

  controller_frequency: 20.0